In [2]:
bir_boyutlu=[1,2,3,4,5]

In [3]:
len(bir_boyutlu)

5

In [4]:
iki_boyutlu=[[1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13]]

In [6]:
eleman_sayisi= len(iki_boyutlu)*len(iki_boyutlu[0])
eleman_sayisi

12

In [7]:
len(iki_boyutlu)

3

In [9]:
satir_sutunsayisi=(len(iki_boyutlu),len(iki_boyutlu[0]))
satir_sutunsayisi

(3, 4)

In [11]:
iki_boyutlu[0][1]

2

In [13]:
iki_boyutlu[2]

[10, 11, 12, 13]

In [14]:
slicing= [satir[1:2]for satir in iki_boyutlu]
slicing

[[2], [6], [11]]

In [15]:
[satir[0:2] for satir in iki_boyutlu]

[[1, 2], [5, 6], [10, 11]]

In [16]:
uc_boyutlu =[[[1, 2, 3],
              [4, 5, 6]],
            [[7, 8, 9],
             [10, 11, 12]
            ]]

In [17]:
len(uc_boyutlu)

2

In [20]:
uc_boyutlu_satir_sutunsayisi=len(uc_boyutlu)*len(uc_boyutlu[0]*len(uc_boyutlu[0][0]))
uc_boyutlu_satir_sutunsayisi

12

In [22]:
uc_boyutlu[0][1][1]

5

In [23]:
uc_boyutlu[0][1]

[4, 5, 6]

In [24]:
slicing_uc_boyutlu=[satir[1:2] for satir in uc_boyutlu]
slicing_uc_boyutlu

[[[4, 5, 6]], [[10, 11, 12]]]

In [1]:
#Numpyfonksiyonu
import numpy as np  
np_birboyut=np.array([1,2,3,4,5,6,7,8,9])

In [2]:
np_birboyut[1]

2

In [3]:
np_birboyut[0:3]

array([1, 2, 3])

In [4]:
np_birboyut[1:7:2]

array([2, 4, 6])

In [5]:
np_ikiboyut=np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]])

In [6]:
np_ikiboyut[1,0]

4

In [7]:
np_ikiboyut[3,2]

12

In [8]:
np_ikiboyut[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np_ikiboyut[0:2:2]

array([[1, 2, 3]])

In [10]:
np_ucboyut = np.array([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])

In [11]:
np_ucboyut[1, 0, 1]

8

In [12]:
np_ucboyut[1:2]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
np_birboyut.shape

(9,)

In [14]:
np_birboyut.size

9

In [15]:
np_ikiboyut.shape

(4, 3)

In [16]:
np_ikiboyut.size

12

In [17]:
np_ucboyut.shape

(2, 2, 3)

In [18]:
np_ucboyut.size

12

In [20]:
zero_array=np.zeros((2,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
bir_array=np.ones((2,3))
bir_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
satır_array = np.concatenate((zero_array, bir_array), axis=0)
satır_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
sutun_array = np.concatenate((zero_array, bir_array), axis=1)
sutun_array

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])